apiVersion: v1
kind: Service
metadata:
  name: front-end-load-balancer
  labels:
    name: front-end-load-balancer   
  namespace: sock-shop
spec:
  type: LoadBalancer
  selector:
    name: front-end
  ports:
  - port: 80
    targetPort: 8079
    name: http-front-end-load-balanced


